on:
  workflow_call:
    inputs:
      tag:
        description: "release tag"
        type: string
        required: true

name: Release

permissions: write-all

jobs:
  create:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ inputs.tag }}
        draft: false
        prerelease: false

  upload:
    runs-on: ubuntu-latest
    needs: create
    strategy:
      matrix:
        include:
          - target: amd64
          - target: arm64
          - target: armhf
    steps:
    - name: Git describe
      id: ghd
      uses: proudust/gh-describe@v2

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: lmdb_${{ inputs.tag }}-1_${{ matrix.target }}.deb

    - name: Upload
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create.outputs.upload_url }}
        asset_path: lmdb_${{ inputs.tag }}-1_${{ matrix.target }}.deb
        asset_name: lmdb_${{ inputs.tag }}-1_${{ matrix.target }}.deb
        asset_content_type: application/vnd.debian.binary-package
